#!/usr/bin/env python3
"""ForensIQ train/predict stage.

Contract:
  Input arguments:
    predict --plugin-output-file <path> [--file-name <string>]
      Reads JSON output generated by plugins.py.
    train [--dataset-file <path>]
      Placeholder training command for explicit train/predict contract support.

  Output on stdout (JSON envelope):
    Success:
      {"status":"success","data":{...}}
    Error:
      {"status":"error","error":{"code":"...","message":"...","details":{...}}}
"""

from __future__ import annotations

import argparse
import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple


def emit(payload: Dict[str, Any], exit_code: int = 0) -> None:
    print(json.dumps(payload, separators=(",", ":"), ensure_ascii=True))
    raise SystemExit(exit_code)


def emit_error(code: str, message: str, details: Dict[str, Any] | None = None) -> None:
    emit(
        {
            "status": "error",
            "error": {
                "code": code,
                "message": message,
                "details": details or {},
            },
        },
        exit_code=1,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="ForensIQ train/predict stage")
    subparsers = parser.add_subparsers(dest="command", required=True)

    predict_parser = subparsers.add_parser("predict", help="Generate prediction from plugins output")
    predict_parser.add_argument("--plugin-output-file", required=True, help="Path to plugins.py JSON output")
    predict_parser.add_argument("--file-name", default="", help="Original filename metadata")

    train_parser = subparsers.add_parser("train", help="Prepare model metadata (no persisted model artifacts)")
    train_parser.add_argument("--dataset-file", default="", help="Optional training dataset path")

    return parser.parse_args()


def clamp_score(value: float) -> int:
    return max(0, min(100, int(round(value))))


def sigmoid(value: float) -> float:
    return 1.0 / (1.0 + math.exp(-value))


def parse_plugins_output(path: Path) -> Dict[str, Any]:
    if not path.exists():
        emit_error("TRAIN_INPUT_NOT_FOUND", "Plugin output file does not exist", {"path": str(path)})

    if not path.is_file():
        emit_error("TRAIN_INPUT_INVALID", "Plugin output path is not a file", {"path": str(path)})

    raw = path.read_text(encoding="utf-8").strip()
    if not raw:
        emit_error("TRAIN_INPUT_EMPTY", "Plugin output file is empty", {"path": str(path)})

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        emit_error(
            "TRAIN_INPUT_JSON_ERROR",
            "Plugin output file is not valid JSON",
            {"path": str(path), "reason": str(exc)},
        )

    if isinstance(payload, dict) and payload.get("status") == "success" and isinstance(payload.get("data"), dict):
        return payload["data"]

    if isinstance(payload, dict) and payload.get("status") == "error":
        emit_error(
            "TRAIN_UPSTREAM_PLUGIN_ERROR",
            "Plugin stage returned an error payload",
            payload.get("error") if isinstance(payload.get("error"), dict) else {},
        )

    if isinstance(payload, dict):
        return payload

    emit_error("TRAIN_INPUT_SCHEMA_ERROR", "Plugin output JSON schema is invalid", {"path": str(path)})
    return {}


def build_rationale(
    threat_score: int, suspicious_count: int, matched_signal_count: int, entropy: float
) -> List[str]:
    rationale: List[str] = []

    if threat_score >= 70:
        rationale.append("Extraction stage threat score is elevated.")
    elif threat_score >= 45:
        rationale.append("Extraction stage threat score is above baseline.")
    else:
        rationale.append("Extraction stage threat score is near baseline.")

    if suspicious_count > 0:
        rationale.append(f"{suspicious_count} suspicious process signatures were observed.")

    if matched_signal_count > 0:
        rationale.append(f"{matched_signal_count} weighted keyword indicators were matched.")

    if entropy >= 7.7:
        rationale.append("Entropy is above high-risk threshold.")
    elif entropy >= 7.2:
        rationale.append("Entropy is moderately elevated.")

    if not rationale:
        rationale.append("Limited malicious indicators were detected in the extracted feature set.")

    return rationale


def derive_prediction(plugins_data: Dict[str, Any]) -> Tuple[Dict[str, Any], Dict[str, Any], List[str]]:
    threat_score = clamp_score(float(plugins_data.get("threat_score", 0)))
    suspicious_processes = plugins_data.get("suspicious_processes") or []
    suspicious_count = len(suspicious_processes) if isinstance(suspicious_processes, list) else 0

    matched_signals = plugins_data.get("metrics", {}).get("matched_signals", [])
    matched_signal_count = len(matched_signals) if isinstance(matched_signals, list) else 0

    entropy = float(plugins_data.get("metrics", {}).get("entropy", 0.0))
    entropy_penalty = max(0.0, entropy - 7.0)

    linear_score = (
        (threat_score * 0.045)
        + (suspicious_count * 0.55)
        + (matched_signal_count * 0.38)
        + (entropy_penalty * 1.4)
        - 3.0
    )

    malicious_probability = max(0.0, min(1.0, sigmoid(linear_score)))
    risk_score = clamp_score(malicious_probability * 100.0)

    if risk_score >= 70:
        label = "Malicious"
    elif risk_score >= 45:
        label = "Suspicious"
    else:
        label = "Benign"

    confidence = malicious_probability if label != "Benign" else 1.0 - malicious_probability
    confidence = round(max(0.0, min(1.0, confidence)), 4)

    rationale = build_rationale(threat_score, suspicious_count, matched_signal_count, entropy)

    recommended_actions = []
    if label in ("Malicious", "Suspicious"):
        recommended_actions.append("Correlate this result with endpoint telemetry for scope validation.")
        recommended_actions.append("Preserve timeline artifacts and triage suspicious process lineage.")
    if label == "Malicious":
        recommended_actions.append("Treat this host as compromised until containment and eradication are complete.")
    if entropy >= 7.7:
        recommended_actions.append("Prioritize reverse engineering for high-entropy payload regions.")

    recommended_actions = list(dict.fromkeys(recommended_actions))

    feature_contribution_labels = [
        "Threat Score Input",
        "Suspicious Processes",
        "Matched Signals",
        "Entropy Elevation",
    ]
    feature_contribution_values = [
        round(threat_score * 0.045, 3),
        round(suspicious_count * 0.55, 3),
        round(matched_signal_count * 0.38, 3),
        round(entropy_penalty * 1.4, 3),
    ]

    chart_datasets = {
        "charts": [
            {
                "id": "prediction_probability",
                "type": "bar",
                "title": "Prediction Probability",
                "description": "Probability split produced by train.py prediction stage.",
                "labels": ["Malicious Probability", "Benign Probability"],
                "values": [
                    round(malicious_probability * 100, 2),
                    round((1.0 - malicious_probability) * 100, 2),
                ],
            },
            {
                "id": "prediction_feature_contributions",
                "type": "bar",
                "title": "Prediction Feature Contributions",
                "description": "Relative contribution of feature groups to the prediction score.",
                "labels": feature_contribution_labels,
                "values": feature_contribution_values,
            },
        ]
    }

    prediction = {
        "label": label,
        "confidence": confidence,
        "risk_score": risk_score,
        "model_version": "heuristic-logistic-v1",
        "primary_reason": rationale[0],
        "rationale": rationale,
    }

    return prediction, chart_datasets, recommended_actions


def run_train_command(dataset_file: str) -> Dict[str, Any]:
    dataset_metadata = {
        "dataset_file": dataset_file or None,
        "dataset_exists": False,
        "sample_rows": None,
    }

    if dataset_file:
        dataset_path = Path(dataset_file)
        dataset_metadata["dataset_exists"] = dataset_path.exists() and dataset_path.is_file()
        if dataset_metadata["dataset_exists"]:
            with dataset_path.open("r", encoding="utf-8", errors="ignore") as handle:
                line_count = sum(1 for _ in handle)
            dataset_metadata["sample_rows"] = max(0, line_count - 1)

    return {
        "pipeline_stages": ["train"],
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "model_version": "heuristic-logistic-v1",
        "dataset": dataset_metadata,
    }


def run_predict_command(plugin_output_file: str, file_name: str) -> Dict[str, Any]:
    plugins_data = parse_plugins_output(Path(plugin_output_file))
    prediction, chart_datasets, recommended_actions = derive_prediction(plugins_data)

    return {
        "pipeline_stages": ["prediction"],
        "file_name": file_name or plugins_data.get("file_name") or "",
        "prediction": prediction,
        "chart_datasets": chart_datasets,
        "recommended_actions": recommended_actions,
    }


def main() -> None:
    args = parse_args()

    try:
        if args.command == "train":
            data = run_train_command(args.dataset_file)
            emit({"status": "success", "data": data}, exit_code=0)
            return

        if args.command == "predict":
            data = run_predict_command(args.plugin_output_file, args.file_name)
            emit({"status": "success", "data": data}, exit_code=0)
            return

        emit_error("TRAIN_COMMAND_INVALID", "Unsupported command", {"command": args.command})
    except SystemExit:
        raise
    except Exception as exc:  # pragma: no cover - defensive error mapping
        emit_error(
            "TRAIN_EXECUTION_ERROR",
            "Prediction stage failed",
            {"exception_type": exc.__class__.__name__, "exception_message": str(exc)},
        )


if __name__ == "__main__":
    main()
